apiVersion: apps/v1
kind: Deployment
metadata:
  name: portkey-gateway
  namespace: tensor-fusion-sys
  labels:
    app: portkey-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portkey-gateway
  template:
    metadata:
      labels:
        app: portkey-gateway
    spec:
      containers:
      - name: portkey-gateway
        image: docker.io/portkeyai/gateway:latest
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 10
        env:
        - name: PORT
          value: "8080"
---
apiVersion: v1
kind: Service
metadata:
  name: portkey-gateway
  namespace: tensor-fusion-sys
spec:
  selector:
    app: portkey-gateway
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP

